language: java

jdk:
  - openjdk17

# Need a full git clone in order to be able to tag the release
git:
  clone: false

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout $TRAVIS_BRANCH
  - POM_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | sed -e 's/-SNAPSHOT//')
  - openssl aes-256-cbc -K $encrypted_044baa266d1a_key -iv $encrypted_044baa266d1a_iv -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
  - gpg --fast-import .travis/gpg.asc

env:
  global:
    # Environment variables referenced in .travis/maven-settings.xml. To encrypt and escape values correctly, run the following
    # command and enter ENV_VAR=value when prompted:
    # read -r && travis encrypt "$(printf %q "$REPLY")"
    - secure: f1XIK8vRHhWQa0Zmho4Wm6kf1B6pLRP8MjaYWweB6hscjv0cSnxm3qdjNo3wl7ciAZQgdM0DUQP6cKyBXuFJegIqTfewC6BY6qATSQ7AVqejbBb7z0QOJBsKotFYgpPi/Osz6GuotT3o9eJnDoU+0XAO3/Zdtc4Ikir4efvN8WAH/msKK/LGWcs2BAaYzDkKNIqjdih6faEV1WU4ZyCKLIslS56BgRmjm497db28poE7noyt8ZsKssJHQNInNTMaMTsjHyUSGxb8qWYV2KV6P1IhYOZ1kJd/v1iXWvk6LlZb5S45HPYQu7PYV8PcBWDbUg/vC9TF7qdWr9sjfF9taNP6SnWEVnn4zJ2takAE1oKPf2/VZ0QrBJBGUVkXkyBC0iu+xugYz7tamSUYGf+9ukhADn9dOBICSSldr0pQSbDgBfHhlqKbfdmewKoUgQWVfyCeWQ7v6Va6Q8fFT2uwXKps3t5GGqNUcsXYSS6e6tUK4Y2peHvO8MkIgX4UNMAkd2UqSlECoqM8J9koV/ISs989lglDkkZte1HyWRSCo/smjiYUWFBLE0qP+KXy20/Ap+uJi3fa7AYTpKEwg3fgmSjS3ohIypIM/OE2/bH6XRxK0rSFndCVW6P9SNp/9rHM5PmQBf4k89lWi92G0VCvunj1MCZlpCV9NnIUHPwJqiI=
    - secure: UFGs6fEO0eH0iTqPGlSKPx7Y7gxOlHae+MzTD8C7dPZFQPvE9M5pe3NyaSiyH0RvatuqbNFQYPqht/DhRcqmsJyNY/CCCFUSd4ynAtF92yzhvLU6BAF3eBUWq+VmleDEJzS29drRFi8OaHEVL399m4HjOWAbIrtO8jkgcN+Qe5OGZ8pgHEER9mRzuqOYkZmUKzbwyfZloLETsDrcxS/2CjtP4JoCXuxiTpJxDpMxkgQE4jrHo0OVl3VJPWKv5ydcWw7/JQ8SGbjBZMjJ63LM1uGbWXZX17PCumpVhAQ+w4Y7e4+SOlF5LIHECORj0K/OE/bVxk/laeqNiaetsfThFmPGZi1qO2JcbIzr4XwGsYS/Zt9FXDlz30kGPiGQByEQYu3FGl6fnG5IdIKb2ILlBBgXen1fTaz6HNePHdg/IQ4m5cjAK1wy7ftbTNyIZ1ElyOQfqh00lTg3OQPDTj2En3MCXAMPf3ePJV4mSRdV4f9jItI44wzMGGFPPQJkMUxzEj3e4JC4Hp22EbAESxFJle4OhRnUSlFEabe9K2XRLYiT+nVjNmd27vdI6FfXFPLMEfqvG5MMfzWgqVrHXIMz6166U2Lj7B3Sahnvr8VCaJhp9kzYKzd+g0+68hHQ8n7tx8akHVpX23PWRtSaSGgXZ1H60w7O21NUPe4f7ieMcBI=
    - secure: fBGXF2E0KRliZeVXsA69FTJPzflwO99ecUl+e9bZcND442UdBcAvKY5fvJUJKiSJs4oRsamWdl5oV+vwxjuEX6zzHd3m0PnFZTtmMbEk1ET0nq+erSN3P9/Yo7BO7WlxxSeh0JEPDYCpsSMQpPBHOyNE7121y3DcC7Hwqo5m8HYH0LRZwPoMzGOsCCY0FwZ6CApTpY6zWkqllp/ahR4Rsik68zQYn9OoQ0dd5uldJruwsMW2hAHpB0Ecnh7YPAgYkxJo6UZbUcAkJ6mPsdk0oC2vx/xVUXxkK1+FkDYZu4E9wuoX+H+LVKIjW9pkO8eHkoJiCfMg1LH8NpRmUX7lKRFD/eYjsXBFeC18ecYoe/bDNJdX6EdG/W1fSlTZHGTOE9jbHXRJK8ccwGLuc+stCtIsDGhWS0USHkOcEeOhhTszAg0zQ0V+dCAu7G8dQJoA6iipOT+XhB+pC839oLpD/I8iHX6zLrCPhyOv6eHhw+crEsXVxDaYr7IkepRiTKtmoPky4sN/alBz7OQlqIFY5Z377d6uWocxFOTakQTq28CLnANyX2NxYcnPmC4nG3Iz2ra2/ips8qTT9dnpTHRh/SGurRlBjPnByqY+ufIPBd+5shnmqBHtcqJmpfh0Kzj8+cBFJv7pPSDUyqPz3hdQKNCGenzO4AlZMejvAwce6Qg=
    - secure: kjo76spDkXF3C2WsmUzNzxCv+nka9RUBTNG7FfklTQRcV87G2F2KzjqctdJq+n0bMhSp2dg2YuiN2QqlO8fnCNVbD1Tf6bgzuZJnpHbynNcMYnIamyMtyKavY7J57bW5FO8bg/vfLMxrq4GRiF0BJ2gRYHOQr2cgJ4JRCzWkreiG8xf3yWWi4WEv7fTcQGvoniD16GiZQqAgeay/pGzbdYl5dYniaqPIGV553i+/L/uZGxoPKF5vpJbCkCEv0io3UVW46wc6YcQgfWnsFkUEYZBgSydqNz/fRXkrFxBWttAgoXyuP/rAkgQK9kiRebYG6Y74L8ZWwCI8IW8Tfn9jm/HWwi3gZrCTj0yEuKNnossKlkFfI9+eWmnEKjh3fBKj+pHTejYWIpUZ2SUnJTR4nv/9yGpJu7WyIn0g2GGhBs3ZrFQvmDCZymAjFfWSLAGKgK+GWY0B73v0PQDUNAgNpHSdmg0HWjmnnRHdfOZ24V4+3R9gFYzS7QL65AP48RtrLuuJOztovtNXNqgVs1C/c8zUAE1I5oiUfHQpLh9Eo+Yqiy/mXZREm/GzsND0XcUW/KjfOaPDIASJmLIegT5eWX457gepsRE/X9andPY897/SXkfOWD6vCqinSP5ZJ+sPtrw2AsgVOpLcLJ4RElNi8nXR/VCbfMPdqRL1EE4DZ14=
    - secure: jFHuFhiWJn/+zftQF/d2tEZ3E27bDGHPnp4uOB7moHdMvMvWKjBjniONB5kpqDjZ+jhUQ70W0ON8cAFbCIBzX6ubCL4Z2cSJ2AbZatWXqDXOnaE9Grmo19gxsJd0Gi/vKl3DxevRNIYi9V8GCszk5SijTDXagcwsPyuqUEfpdrGiKa/wUByEl9A0ViN+jB9X3H/dGkwCdwCSoQRAfY+PSXSiaP4pYdEaBjpBVMAElbKmroJOsI4P7t9bznZyRElqpLBF9vwey1nLfjPWQVRebkLBpYVUm3uh59q6i4Q647+ceUzFNLmUeOOEUF9p2U2eQMrPLjw5/65Cg4Q0FIuzmxfCIBR8FSBo1kSyngwxm3OzzMyGABCbgarTTo+q7QFMyVW7EXPx97goM+HzITUEDRbYlNAa6gTB/eNSsheByGJro40PGgd/1RssZgIOwqjqHqILT8l23X0W/ojwuBV5p3m7RYi3OHDdqm9Nbc4oRMxO6YecATwq1tLwt7NSqj1OYjJvN+yazBvRMVpIHi1PQJlaYVNPKO+MA/qat9UrTiODu2DFt/iqr2i+AYa042WGC+AbahuLB9TlEkBm92iWyL4ci8sQFGZnVS9b6ea1yqHKktsgacvT018UOhHu5MTzxkYjGN98kC4GYeL16Q4YjogcIYbWSfDwCRdeKezuLYw=

script:
  - mvn clean install -B
  - mvn org.pitest:pitest-maven:mutationCoverage -B

before_deploy:
  # Set tag to be used by releases provider
  - export TRAVIS_TAG=$POM_VERSION

deploy:
  # For any checkin to main branch, create a final version, tag it and push the artifacts to Sonatype
  - provider: script
    skip_cleanup: true
    script:
      mvn --settings .travis/maven-settings.xml release:prepare release:perform -DskipTests -Prelease -B
    on:
      branch: main

  # Releases config copied from https://docs.travis-ci.com/user/deployment/releases/ and secure key generated by following
  # https://stackoverflow.com/questions/25302518/travis-ci-setup-releases-with-github-token#answer-57032190
  - provider: releases
    api_key:
      secure: OnamPE3tieG5jUSUxH1RQMnpn4cSt8er+4kL+uacLzVy6oeKYFgiSlKU4ZZ4tda1F0JiDTf5zokIlwYycRxZLHjN827EGqMfL2dSUhbWA7Fakk3J/V23Q2wvWJSqoTPikaLPjKbD4WfcQA9sHFTU6rojAoIZ8xICuJYc6ZmPcsAH/pHx3NfLEsGYW4QJK21IOjcUYNI5DwnafTXwaur+wYiaroPJRMRt2Ve22cZ48j7dXHg+vaxWPh+VUj1Uw1yDXnB6xkzFlu0hDO3ZuoCBX2NXJJVKue68W/yBE8AcqepQdqQAnO+fK9rRyVfRRx7KkwKJQurCLX56j100gHhmkmF0H3oTvK3Y4Gh6HM8HCio0ZbiiySABwbsGewO/idOIGPARUyjELLEDWE7TEu1j4soy9N+D9TmOofshGhtEwc+Yim1o4AhCptWJxnn6wETwjOxaUVMZIxfYBM2PSF13R0Y3K8Aiw3tTnPRmM7P1Qi9+fiXj2bTScY+Nhh6QKFfOIqfm+mssepeNQ/NI+3hPAeytPnlL3KDAh1jNFuHtt7mFVpPK65cKIQydejRJYkyg9kvrg4yzC+Hp5/XOz98arqVEhlzbm4SzaT5uxZURrmRv+6IWwTjaEIFN5RUAm8+HHyGjUHjxgZ/P7RPeOK8SB16GjifSV5wTbOBXuQIwOT4=
    file: "target/spt-development-cid-${POM_VERSION}.jar"
    skip_cleanup: true
    on:
      branch: main